# Generated by Django 4.0.4 on 2022-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_subject', models.CharField(max_length=100)),
                ('love_to_do', models.CharField(max_length=100)),
                ('fav_colour', models.CharField(max_length=100)),
                ('fav_game', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
    ]
